export const domainToTag: Record<string, string> = {
  "iiits.ac.in": "IIIT SRICITY",
  "iiits.in": "IIIT SRICITY",
  "iiitt.ac.in": "IIIT TRICHY",
  "iiitt.in": "IIIT TRICHY",
  "iiitu.ac.in": "IIIT UNA",
  "iiitu.in": "IIIT UNA",
  "iiit-bh.ac.in": "IIIT BHUBANESWAR",
  "iiit-bh.in": "IIIT BHUBANESWAR",
  "iiitkota.ac.in": "IIIT KOTA",
  "iiitkota.in": "IIIT KOTA",
  "iiitsurat.ac.in": "IIIT SURAT",
  "iiitsurat.in": "IIIT SURAT",
  "iiitkottayam.ac.in": "IIIT KOTTAYAM",
  "iiitkottayam.in": "IIIT KOTTAYAM",
  "iiitvadodara.ac.in": "IIIT VADODARA",
  "iiitvadodara.in": "IIIT VADODARA",
  "iiitbh.ac.in": "IIIT BHAGALPUR",
  "iiitbh.in": "IIIT BHAGALPUR",
  "iiitbhopal.ac.in": "IIIT BHOPAL",
  "iiitbhopal.in": "IIIT BHOPAL",
  "iiitnr.ac.in": "IIIT NAYA RAIPUR",
  "iiitnr.in": "IIIT NAYA RAIPUR",
  "iiitsonepat.ac.in": "IIIT SONEPAT",
  "iiitsonepat.in": "IIIT SONEPAT",
  "iiitr.ac.in": "IIIT RAICHUR",
  "iiitr.in": "IIIT RAICHUR",
  "iiitk.ac.in": "IIIT KURNOOL",
  "iiitk.in": "IIIT KURNOOL",
  "iiitmanipur.ac.in": "IIIT MANIPUR",
  "iiitmanipur.in": "IIIT MANIPUR",
  "iiitagartala.ac.in": "IIIT AGARTALA",
  "iiitagartala.in": "IIIT AGARTALA",
  "iiitn.ac.in": "IIIT NAGPUR",
  "iiitn.in": "IIIT NAGPUR",
  "iiitd.ac.in": "IIIT DELHI",
  "iiitd.in": "IIIT DELHI",
  "iiitdwd.ac.in": "IIIT DHARWAD",
  "iiitdwd.in": "IIIT DHARWAD",
  "iiita.ac.in": "IIIT ALLAHABAD",
  "iiita.in": "IIIT ALLAHABAD",
  "iiitl.ac.in": "IIIT LUCKNOW",
  "iiitl.in": "IIIT LUCKNOW",
  "diu.iiitvadodara.ac.in": "IIIT DIU",
  "diu.iiitvadodara.in": "IIIT DIU",
  "iiitkalyani.ac.in": "IIIT KALYANI",
  "iiitkalyani.in": "IIIT KALYANI",
};
